version: "3"
services:
  webapp:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - mynetwork
  backend:
    image: node:14
    working_dir: /app
    volumes:
      - ./backend:/app
    networks:
      - mynetwork
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
  legacy_mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: legacyroot
      MYSQL_DATABASE: legacydb
      MYSQL_USER: legacyuser
      MYSQL_PASSWORD: legacypassword
    networks:
      - mynetwork
networks:
  mynetwork:
volumes:
  pgdata: